apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: manager-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: manager-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: manager-backend
          image: docker.io/fabrizio294/manager:0.0.6
          ports:
            - containerPort: 8000
          env:
            - name: "KAFKA_HOST"
              value: "local-cluster-kafka-bootstrap.kafka.svc:9092"
            - name: "KAFKA_GROUP"
              value: tesi