apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kafka
  namespace: backend
spec:
  selector:   
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/confluentinc/cp-kafka:7.0.1
        port: 
          - containerPort: 9092
            protocol: TCP
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT 
          value: localhost:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:9092
        - name: KAFKA_BROKER_ID
          value: 2
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: 1

      - name: zookeeper
        image: docker.io/confluentinc/cp-zookeeper:7.0.1
        env:
        - name: ZOOKEEPER_ADMIN_ENABLE_SERVER 
          value: false
        - name: ZOOKEEPER_CLIENT_PORT
          value: 2181
        - name: ZOOKEEPER_TICK_TIME
          value: 2000
        - name: ZOOKEEPER_SYNC_LIMIT
          value: 2
