spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    inetutils:
      timeout-seconds: 10
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length : 104857600
      routes: 
        # Favicon
        - id: favicon
          uri: forward:///favicon.ico
          predicates:
            - Path=**/favicon.ico
        # fe 
        - id: frontend
          predicates:
            - Path=/web/**
          filters:
            - CheckAuth
            - TokenRelayFilter
            # - RewritePath=/web(?<segment>/?.*), $\{segment}
          uri: http://localhost:3000
        # Activity service
        - id: rest-service
          predicates:
            - Path=/api/**
          uri: http://localhost:8000
          filters:
           - CheckAuth
           - TokenRelayFilter
server:
  port: 7080
  netty:
    max-initial-line-length : 50MB

logging:
  level:
    root: INFO
    
auth:
  enable: true
  mockrole: ADMIN
  showjwt: true
  secret:  GT3hnCJb9AxkidHjdxvDk80rNfXn4Bth
  
keycloack:
  realm: Tesi
  clientid: tesi-client
  feingress: http://192.168.230.129:7080
  oidcaddr: http://192.168.230.129:30090