apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: databases
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS Tesi;
    CREATE DATABASE IF NOT EXISTS keycloak;

    CREATE USER '{{ .Values.global.mySqlUserKeycloak }}'@'%' IDENTIFIED BY '{{ .Values.global.mySqlPwdKeycloak }}';
    GRANT ALL PRIVILEGES ON keycloak.* TO '{{ .Values.global.mySqlUserKeycloak }}'@'%';

    USE Tesi;
    CREATE TABLE IF NOT EXISTS input_entities (
        Id bigint NOT NULL AUTO_INCREMENT,
        name varchar(50) NOT NULL,
        description varchar(100) DEFAULT NULL,
        amplitude decimal(6,3) NOT NULL DEFAULT 0,
        frequency decimal(6,3) NOT NULL DEFAULT 0,
        function varchar(10) NOT NULL,
        enable tinyint(1) NOT NULL DEFAULT 0,
        agent_id varchar(100) NOT NULL,
        PRIMARY KEY (Id)
    );