apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: databases
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
