{{- $simReplicas := .Values.global.simulatoreReplicas | default .Values.simulatore.replicas -}}

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: simulatore
  namespace: monitoring
spec:
  selector:   
    matchLabels:
      app: simulatore
  replicas: 1
  template:
    metadata:
      labels:
        app: simulatore
    spec:
      containers:
      {{- range  $i, $e := untilStep 0 (int ($simReplicas)) 1 }} 
      - name: "{{- printf "%s%d" "simulatore" $i -}}"
        image: localhost:5000/fabrizio294/simulatore:0.0.7
        env:
        - name: "KAFKA_HOST"
          value: "local-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: "MATH_FUN"
          value: {{ if eq (mod $i 2) 0}} sin {{ else }} cos {{ end }}
        - name: "AMPLITUDE"
          value: "{{ add $i 1 }}"
        - name: "FREQUENCY"
          value: "{{ add $i 1 }}"
      {{- end }}