{{- $simReplicas := .Values.global.simulatoreReplicas | default .Values.simulatore.replicas -}}


apiVersion: apps/v1 
kind: Deployment
metadata:
  name: simulatore
  namespace: monitoring
spec:
  selector:   
    matchLabels:
      app: simulatore
  replicas: 1
  template:
    metadata:
      labels:
        app: simulatore
    spec:
      containers:
      {{- range  $i, $e := untilStep 0 $simReplicas 1 }} 
      - name: simulatore
        image: docker.io/fabrizio294/simulatore:latest
        env:
        - name: "kafka__host"
          value: "dns kube kafka"
        - name: "math__fun"
          value: {{ if eq (mod $i 2) 0}} sin {{ else }} cos {{ end }}
        - name: "amplitude"
          value: add $i 1
        - name: "frequency"
          value: add $i 1
      {{- end }}
