apiVersion: apps/v1 
kind: Deployment
metadata:
  name: config-scheduler
  namespace: frontend
spec:
  selector:   
    matchLabels:
      app: config-scheduler
  template:
    metadata:
      labels:
        app: config-scheduler
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: "config-scheduler"
        image: docker.io/fabrizio294/configuration-scheduler:0.1.0
        ports:
        - containerPort: 8001
        env:
        - name: "KAFKA_BOOTSTRAP-SERVERS"
          value: "{{ .Values.global.internalKafkaFqdn }}:{{ .Values.global.internalKafkaPort }}"
        - name: "SPRING_PROFILES_ACTIVE"
          value: "prod"
        - name: "SPRING_KAFKA_CONSUMER_GROUP-ID"
          value: tesi
        - name: "SPRING_DATASOURCE_URL"
          value: "jdbc:mysql://{{ .Values.global.mySqlHost }}:{{ .Values.global.mySqlPort }}/{{ .Values.global.mySqlDb }}?useLegacyDatetimeCode=false&serverTimezone=Europe/Rome"
        - name: "SPRING_DATASOURCE_USERNAME"
          valueFrom:
            secretKeyRef:
              name: rest-secret
              key: usernameSql
        - name: "SPRING_DATASOURCE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: rest-secret
              key: passwordSql

