apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rest
  namespace: frontend
spec:
  selector:   
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: "rest"
        image: docker.io/fabrizio294/rest-service:0.0.10
        ports:
        - containerPort: 8000
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "prod"
        - name: "SPRING_DATASOURCE_URL"
          value: "jdbc:mysql://{{ .Values.global.mySqlHost }}:{{ .Values.global.mySqlPort }}/{{ .Values.global.mySqlDb }}?useLegacyDatetimeCode=false&serverTimezone=Europe/Rome"
        - name: "BUSINNESS_MANAGER_URL"
          # value: "http://192.168.230.129:8000"
          value: "http://{{ .Values.global.manager.dns }}:{{ .Values.global.manager.port }}"
        - name: "SPRING_DATASOURCE_USERNAME"
          valueFrom:
            secretKeyRef:
              name: rest-secret
              key: usernameSql
        - name: "SPRING_DATASOURCE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: rest-secret
              key: passwordSql
        - name: "AUTH_ENABLE"
          value: "{{ .Values.global.authEnable }}"
        {{ if eq .Values.global.authEnable false }}
        - name: "AUTH_MOCKROLE"
          value: "admin"
        {{ end }}
        - name: "AUTH_SECRET"
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: secretOidc