apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: password
        - name: KC_PROXY
          value: "edge"
        - name: "DB_VENDOR"
          value: "mysql"
        - name: "DB_ADDR"
          value: "{{ .Values.global.mySqlHost }}"
        - name: "DB_PORT"
          value: "{{ .Values.global.mySqlPort }}"
        - name: "DB_DATABASE"
          value: "keycloak"
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: usernameSql
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: passwordSql 
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque 
stringData:
  username: "keyckloak_admin"
  password: "K3ycl04k-Pwd&"
  usernameSql: {{ .Values.global.mySqlUserKeycloak }}
  passwordSql: {{ .Values.global.mySqlPwdKeycloak }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    name: keycloak