apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    
    
    datasources:
    - name: Prometheus-kafkaExp
      type: prometheus
      url: http://prometheus-service.monitoring.svc:9090
      access: proxy
      isDefault: true
      editable: true

    - name: InfluxDB_v2_Flux
      type: influxdb
      access: proxy
      url: http://influxdb.influx.svc:8086
      user: {{ .Values.global.influxUsername }}
      jsonData:
        version: Flux
        organization: {{ .Values.global.influxOrg }}
        defaultBucket: {{ .Values.global.influxBucket }}
        tlsSkipVerify: true
      secureJsonData:
        token: {{ .Values.global.influxAdminToken }}