apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: monitoring
spec:
  selector:
    app: manager
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP