apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
  - protocol: TCP
    name: rest
    port: 8000
    targetPort: 8000
