apiVersion: v1
kind: Secret
metadata:
  name: telegraf-influx-secret
  namespace: influx
type: Opaque 
stringData:
  usernameInflux: {{ .Values.global.influxUsername }}
  passwordInflux: {{ .Values.global.influxPasswd }}